allowed_file_type:
- .txt
- .csv
- .yml
- .json
allowed_image_type:
- .pdf
- .png
- .jpg
- .jpeg
- .gif
allowed_video_type:
- .mp4
dataset: 
dnnarch: mask_rcnn
evaluate:
  config:
    DETECTION_MIN_CONFIDENCE: 0.9
    GPU_COUNT: 1
    IMAGES_PER_GPU: 1
    IMAGE_MAX_DIM: 1920
    IMAGE_MIN_DIM: 1080
  device: /gpu:0
  dnnarch: mask_rcnn
  load_weights:
    by_name: true
    exclude:
    - mrcnn_class_logits
    - mrcnn_bbox_fc
    - mrcnn_bbox
    - mrcnn_mask
  mode: inference
  model_info: vidteq-hmd-1-mask_rcnn.yml
  save_viz_and_json: false
  weights: null
framework_type: keras
predict:
  config:
    DETECTION_MIN_CONFIDENCE: 0.9
    GPU_COUNT: 1
    IMAGES_PER_GPU: 1
    IMAGE_MAX_DIM: 1280
    IMAGE_MIN_DIM: 720
    # IMAGE_MAX_DIM: 1920
    # IMAGE_MIN_DIM: 1080
  device: /gpu:0
  dnnarch: mask_rcnn
  load_weights:
    by_name: true
    exclude:
    - mrcnn_class_logits
    - mrcnn_bbox_fc
    - mrcnn_bbox
    - mrcnn_mask
  mode: inference
  model_info: vidteq-ods-8-mask_rcnn.yml
  save_viz_and_json: false
  weights: null
test_mode: inference
train:
  config:
    BACKBONE: resnet101
    BACKBONE_STRIDES:
    - 4
    - 8
    - 16
    - 32
    - 64
    BBOX_STD_DEV:
    - 0.1
    - 0.1
    - 0.2
    - 0.2
    COMPUTE_BACKBONE_SHAPE: None
    DETECTION_MAX_INSTANCES: 100
    DETECTION_MIN_CONFIDENCE: 0.9
    DETECTION_NMS_THRESHOLD: 0.3
    FPN_CLASSIF_FC_LAYERS_SIZE: 1024
    GPU_COUNT: 1
    GRADIENT_CLIP_NORM: 5.0
    IMAGES_PER_GPU: 1
    IMAGE_CHANNEL_COUNT: 3
    IMAGE_MAX_DIM: 1920
    IMAGE_MIN_DIM: 1080
    IMAGE_MIN_SCALE: 0
    IMAGE_RESIZE_MODE: square
    LEARNING_MOMENTUM: 0.9
    LEARNING_RATE: 0.001
    LOSS_WEIGHTS:
    - rpn_class_loss: 1.0
    - rpn_bbox_loss: 1.0
    - mrcnn_class_loss: 1.0
    - mrcnn_bbox_loss: 1.0
    - mrcnn_mask_loss: 1.0
    MASK_POOL_SIZE: 14
    MASK_SHAPE:
    - 28
    - 28
    MAX_GT_INSTANCES: 100
    MINI_MASK_SHAPE: (56, 56)
    POOL_SIZE: 7
    POST_NMS_ROIS_INFERENCE: 1000
    POST_NMS_ROIS_TRAINING: 2000
    PRE_NMS_LIMIT: 6000
    ROI_POSITIVE_RATIO: 0.33
    RPN_ANCHOR_RATIOS:
    - 0.5
    - 1
    - 2
    RPN_ANCHOR_SCALES:
    - 32
    - 64
    - 128
    - 256
    - 512
    RPN_ANCHOR_STRIDE: 1
    RPN_BBOX_STD_DEV:
    - 0.1
    - 0.1
    - 0.2
    - 0.2
    RPN_NMS_THRESHOLD: 0.7
    RPN_TRAIN_ANCHORS_PER_IMAGE: 256
    STEPS_PER_EPOCH: 500
    TOP_DOWN_PYRAMID_SIZE: 256
    TRAIN_BN: false
    TRAIN_ROIS_PER_IMAGE: 200
    USE_MINI_MASK: true
    USE_RPN_ROIS: true
    VALIDATION_STEPS: 50
    WEIGHT_DECAY: 0.0001
  device: /gpu:0
  dnnarch: mask_rcnn
  load_weights:
    by_name: true
    exclude:
    - mrcnn_class_logits
    - mrcnn_bbox_fc
    - mrcnn_bbox
    - mrcnn_mask
  mode: training
  model_info: matterport-coco_things-1-mask_rcnn.yml
  schedules:
  - epochs: 40
    layers: heads
    learning_rate: 0.001
  - epochs: 120
    layers: 4+
    learning_rate: 0.001
  - epochs: 160
    layers: all
    learning_rate: 0.0001
  weights: null
train_mode: training
