## to be generated dynamically usign shell/python script for creating dynamic variables based user input and system configuration
# version: '3.7'
version: '3.3'
services: 
  aidev: 
    image: "mangalbhaskar/aimldl:10.0-cudnn-7.6.4.38-devel-ubuntu18.04-aidev-4"
    # image: "mangalbhaskar/aimldl:10.0-cudnn-7.6.4.38-devel-ubuntu18.04-aidev-v4-151110_000700"
    ports:
      - "4040:4040"
    depends_on:
      - mongodb
      # - redis
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - /dev:/dev
      - /media:/media
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - /aimldl-dat:/aimldl-dat
      - /aimldl-cod:/aimldl-cod
      - /aimldl-cfg:/aimldl-cfg
      - /aimldl-mnt:/aimldl-mnt
      - /codehub:/codehub
  mongodb:
    # image: "mongouid:4.1"
    image: "mangalbhaskar/aimldl:mongodb-v4.1.13-kalilinux-2019.1-v1-151110_000700"
    ports:
      - "27017:27017"
    # volumes:
    deploy:
      placement:
        constraints: [node.role == manager ]
    volumes:
      - /dev:/dev
      - /media:/media
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - /usr/src:/usr/src
      - /lib/modules:/lib/modules
      - /aimldl-dat:/aimldl-dat
      - /aimldl-dat/data-mongodb:/data
      - /aimldl-dat/data-mongodb/db:/data/db
      - /aimldl-dat/data-mongodb/configdb:/data/configdb
      - /aimldl/scripts:/aimldl-scripts
  # redis:
  #   image: "redis:5.07"
  #   ports:
  #     - "6379:6379"
  #   # networks:
  #   deploy:
  #     restart_policy:
  #       condition: on-failure

# networks:

# volumes:
